// Modelo para representar información de monedas y tipos de cambio
class Currency {
  final String code;
  final String name;

  const Currency({
    required this.code,
    required this.name,
  });

  @override
  String toString() => '$code ($name)';
}

// Mapa de nombres de monedas para mostrar información más amigable
class CurrencyData {
  // Un mapeo más extenso de códigos de moneda a nombres completos
  static const Map<String, String> currencyNames = {
    'AED': 'Dirham de Emiratos Árabes Unidos',
    'AFN': 'Afgani afgano',
    'ALL': 'Lek albanés',
    'AMD': 'Dram armenio',
    'ANG': 'Florín antillano neerlandés',
    'AOA': 'Kwanza angoleño',
    'ARS': 'Peso argentino',
    'AUD': 'Dólar australiano',
    'AWG': 'Florín arubeño',
    'AZN': 'Manat azerbaiyano',
    'BAM': 'Marco convertible de Bosnia y Herzegovina',
    'BBD': 'Dólar de Barbados',
    'BDT': 'Taka bangladesí',
    'BGN': 'Lev búlgaro',
    'BHD': 'Dinar bareiní',
    'BIF': 'Franco burundés',
    'BMD': 'Dólar bermudeño',
    'BND': 'Dólar de Brunéi',
    'BOB': 'Boliviano',
    'BRL': 'Real brasileño',
    'BSD': 'Dólar bahameño',
    'BTC': 'Bitcoin',
    'BTN': 'Ngultrum butanés',
    'BWP': 'Pula botsuano',
    'BYN': 'Rublo bielorruso',
    'BZD': 'Dólar beliceño',
    'CAD': 'Dólar canadiense',
    'CDF': 'Franco congoleño',
    'CHF': 'Franco suizo',
    'CLF': 'Unidad de Fomento chilena',
    'CLP': 'Peso chileno',
    'CNH': 'Yuan chino (offshore)',
    'CNY': 'Yuan chino',
    'COP': 'Peso colombiano',
    'CRC': 'Colón costarricense',
    'CUC': 'Peso cubano convertible',
    'CUP': 'Peso cubano',
    'CVE': 'Escudo caboverdiano',
    'CZK': 'Corona checa',
    'DJF': 'Franco yibutiano',
    'DKK': 'Corona danesa',
    'DOP': 'Peso dominicano',
    'DZD': 'Dinar argelino',
    'EGP': 'Libra egipcia',
    'ERN': 'Nakfa eritreo',
    'ETB': 'Birr etíope',
    'EUR': 'Euro',
    'FJD': 'Dólar fiyiano',
    'FKP': 'Libra malvinense',
    'GBP': 'Libra esterlina',
    'GEL': 'Lari georgiano',
    'GGP': 'Libra de Guernsey',
    'GHS': 'Cedi ghanés',
    'GIP': 'Libra gibraltareña',
    'GMD': 'Dalasi gambiano',
    'GNF': 'Franco guineano',
    'GTQ': 'Quetzal guatemalteco',
    'GYD': 'Dólar guyanés',
    'HKD': 'Dólar de Hong Kong',
    'HNL': 'Lempira hondureño',
    'HRK': 'Kuna croata',
    'HTG': 'Gourde haitiano',
    'HUF': 'Forinto húngaro',
    'IDR': 'Rupia indonesia',
    'ILS': 'Nuevo séquel israelí',
    'IMP': 'Libra manesa',
    'INR': 'Rupia india',
    'IQD': 'Dinar iraquí',
    'IRR': 'Rial iraní',
    'ISK': 'Corona islandesa',
    'JEP': 'Libra de Jersey',
    'JMD': 'Dólar jamaicano',
    'JOD': 'Dinar jordano',
    'JPY': 'Yen japonés',
    'KES': 'Chelín keniano',
    'KGS': 'Som kirguís',
    'KHR': 'Riel camboyano',
    'KMF': 'Franco comorense',
    'KPW': 'Won norcoreano',
    'KRW': 'Won surcoreano',
    'KWD': 'Dinar kuwaití',
    'KYD': 'Dólar de las Islas Caimán',
    'KZT': 'Tenge kazajo',
    'LAK': 'Kip laosiano',
    'LBP': 'Libra libanesa',
    'LKR': 'Rupia de Sri Lanka',
    'LRD': 'Dólar liberiano',
    'LSL': 'Loti lesotense',
    'LYD': 'Dinar libio',
    'MAD': 'Dírham marroquí',
    'MDL': 'Leu moldavo',
    'MGA': 'Ariary malgache',
    'MKD': 'Denar macedonio',
    'MMK': 'Kyat birmano',
    'MNT': 'Tugrik mongol',
    'MOP': 'Pataca de Macao',
    'MRO': 'Ouguiya mauritano',
    'MRU': 'Ouguiya mauritano',
    'MUR': 'Rupia mauriciana',
    'MVR': 'Rufiyaa maldiva',
    'MWK': 'Kwacha malauí',
    'MXN': 'Peso mexicano',
    'MYR': 'Ringgit malayo',
    'MZN': 'Metical mozambiqueño',
    'NAD': 'Dólar namibio',
    'NGN': 'Naira nigeriano',
    'NIO': 'Córdoba nicaragüense',
    'NOK': 'Corona noruega',
    'NPR': 'Rupia nepalí',
    'NZD': 'Dólar neozelandés',
    'OMR': 'Rial omaní',
    'PAB': 'Balboa panameño',
    'PEN': 'Sol peruano',
    'PGK': 'Kina de Papúa Nueva Guinea',
    'PHP': 'Peso filipino',
    'PKR': 'Rupia pakistaní',
    'PLN': 'Złoty polaco',
    'PYG': 'Guaraní paraguayo',
    'QAR': 'Riyal catarí',
    'RON': 'Leu rumano',
    'RSD': 'Dinar serbio',
    'RUB': 'Rublo ruso',
    'RWF': 'Franco ruandés',
    'SAR': 'Riyal saudí',
    'SBD': 'Dólar de las Islas Salomón',
    'SCR': 'Rupia seychelense',
    'SDG': 'Libra sudanesa',
    'SEK': 'Corona sueca',
    'SGD': 'Dólar de Singapur',
    'SHP': 'Libra de Santa Elena',
    'SLL': 'Leone de Sierra Leona',
    'SOS': 'Chelín somalí',
    'SRD': 'Dólar surinamés',
    'SSP': 'Libra sursudanesa',
    'STD': 'Dobra de Santo Tomé y Príncipe',
    'STN': 'Dobra de Santo Tomé y Príncipe',
    'SVC': 'Colón salvadoreño',
    'SYP': 'Libra siria',
    'SZL': 'Lilangeni suazi',
    'THB': 'Baht tailandés',
    'TJS': 'Somoni tayiko',
    'TMT': 'Manat turcomano',
    'TND': 'Dinar tunecino',
    'TOP': 'Pa\' anga tongano',
    'TRY': 'Lira turca',
    'TTD': 'Dólar de Trinidad y Tobago',
    'TWD': 'Nuevo dólar taiwanés',
    'TZS': 'Chelín tanzano',
    'UAH': 'Grivna ucraniana',
    'UGX': 'Chelín ugandés',
    'USD': 'Dólar estadounidense',
    'UYU': 'Peso uruguayo',
    'UZS': 'Som uzbeko',
    'VEF': 'Bolívar venezolano',
    'VES': 'Bolívar soberano venezolano',
    'VND': 'Đồng vietnamita',
    'VUV': 'Vatu vanuatuense',
    'WST': 'Tala samoano',
    'XAF': 'Franco CFA de África Central',
    'XAG': 'Plata (onza troy)',
    'XAU': 'Oro (onza troy)',
    'XCD': 'Dólar del Caribe Oriental',
    'XDR': 'Derechos Especiales de Giro',
    'XOF': 'Franco CFA de África Occidental',
    'XPD': 'Paladio (onza troy)',
    'XPF': 'Franco CFP',
    'XPT': 'Platino (onza troy)',
    'YER': 'Rial yemení',
    'ZAR': 'Rand sudafricano',
    'ZMW': 'Kwacha zambiano',
    'ZWL': 'Dólar zimbabuense',
  };

  // Lista de monedas populares para usar como predeterminadas
  static const List<String> popularCurrencies = [
    'USD', 'EUR', 'GBP', 'JPY', 'CNY', 'AUD', 'CAD', 'CHF', 'HKD', 'SGD',
    'MXN', 'BRL', 'INR', 'RUB', 'KRW', 'TRY', 'ZAR', 'SEK', 'NOK', 'DKK',
    'PLN', 'THB', 'IDR', 'HUF', 'CZK', 'ILS', 'CLP', 'PHP', 'AED', 'COP',
    'SAR', 'MYR', 'RON', 'BGN', 'PEN', 'ARS'
  ];

  // Lista de códigos de monedas para gráficos (versión reducida)
  static const List<String> chartCurrencies = [
    'USD', 'EUR', 'GBP', 'JPY', 'CNY', 'AUD', 'CAD', 'CHF', 'MXN', 'BRL'
  ];

  // Obtener todas las monedas como objetos Currency
  static List<Currency> getAllCurrencies() {
    return currencyNames.entries
        .map((entry) => Currency(
              code: entry.key,
              name: entry.value,
            ))
        .toList();
  }

  // Obtener moneda por código
  static Currency getCurrency(String code) {
    return Currency(
      code: code,
      name: currencyNames[code] ?? code,
    );
  }
}